USE [FarmCentralDB]
GO
/****** Object:  Table [dbo].[EMPLOYEE]    Script Date: 2023/05/20 11:07:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[EMPLOYEE](
	[EMPLOYEE_ID] [varchar](12) NOT NULL,
	[EMP_NAME] [varchar](225) NOT NULL,
	[EMP_SURNAME] [varchar](225) NOT NULL,
	[EMP_EMAIL] [varchar](225) NOT NULL,
	[EMP_PASSWORD] [varchar](225) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[EMPLOYEE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FARMER]    Script Date: 2023/05/20 11:07:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FARMER](
	[FARMER_ID] [varchar](12) NOT NULL,
	[NAME] [varchar](225) NOT NULL,
	[SURNAME] [varchar](225) NOT NULL,
	[EMAIL] [varchar](225) NOT NULL,
	[PASSWORD] [varchar](225) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[FARMER_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[FARMER_PRODUCTS]    Script Date: 2023/05/20 11:07:25 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[FARMER_PRODUCTS](
	[PRODUCT_ID] [varchar](12) NOT NULL,
	[P_NAME] [varchar](225) NOT NULL,
	[P_PRICE] [varchar](225) NOT NULL,
	[P_QUANTITY] [varchar](225) NOT NULL,
	[FARMER_ID] [varchar](12) NULL,
PRIMARY KEY CLUSTERED 
(
	[PRODUCT_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[FARMER_PRODUCTS]  WITH CHECK ADD FOREIGN KEY([FARMER_ID])
REFERENCES [dbo].[FARMER] ([FARMER_ID])
GO
